### ISSUE TITLE
9. 개발 환경 설정

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/ec_mall#18]
**[ Context ]**
- 개발을 시작하려고 보니, Database 연결에 대한 설정이 필요해졌다.
- 개발을 시작하려고 보니, 멘토가 lombok 등에 대해 알아보라고 했다.

**[ Definition of Done ]**
- Mybatis 설정을 Spring 에 한다. 그 후에, Spring 에서 Mybatis 를 통해 DB 에 접근이 가능한지 확인한다.
- Lombok 을 설정한다

**Comment by SongHeeL** [comment]
Lombok
- Project Lombok은 Java 개발의 속도를 높이고, 편집기와 빌드 도구에 자동으로 연결되는 자바 라이브러리의 플러그인이다.
  getter, setter, equals 등의 메소드와 동등하게 작동하는 기능을 어노테이션만으로 적용할 수 있는 강력한 기능을 말한다.
  즉, 반복되는 메소드를 어노테이션을 사용하여 자동으로 작성해주는 라이브러리이다.
  참고 : https://projectlombok.org/

장점
- 코드 자동 생성을 통한 생상성 향상
- 반복되는 코드를 줄여 가독성 및 유지보수성 향상

단점
- 프로젝트를 작업하는 모든 사람들은 Lombok 플러그인을 설치해야 한다.
- Lombok 중단 시, 롤백에 오랜 시간이 걸린다.
- 참고 : https://blogg.itverket.no/to-lombok-or-not-to-lombok/
