### ISSUE TITLE
10. 프로젝트 폴더 구조

### ISSUE THREAD

**Issue by f-lab-robert** [f-lab-edu/ec_mall#19]
**[ Context ]**
- 프로젝트를 시작하려고 보니 어떻게 할지 모르겠다
- 폴더 구조를 먼저 생각함으로써 API 개발 등을 미리 점검한다.
- 폴더 구조를 멘토, 다른 멘티들과 상의함으로써 프로젝트를 어떻게 시작할지 명확하게 구체화한다.

**[ Definition of Done ]**
- 브랜치를 하나 만들어서, 폴더만 생성하고 멘토에게 PR 리뷰를 요청한다.
- 폴더 구조를 생성하는데 있어서 팀 멘티와 상의한다.

**Comment by SongHeeL** [comment]
![폴더구조](https://user-images.githubusercontent.com/108327480/196707810-1bb34716-3271-4259-a0eb-55b802c88fd9.png)

### 해당 구조로 생성하는 이유
- 수직적 구조로 각 계층의 클래스들을 한번에 확인할 수 있고 우리 서비스의 경우 큰 서비스가 아니기 때문에 해당 구조로 생성해서 사용해도 될 것 같다고 판단하여 위의 이미지 처럼 생성하려고 한다.

**Comment by sypatrick** [comment]
https://github.com/f-lab-edu/ec_mall/pull/21

패키지 pr 리뷰 요청했습니다.
