### ISSUE TITLE
AWS 서버 생성 후 MySQL 설치

### ISSUE THREAD

**Issue by SongHeeL** [f-lab-edu/ec_mall#5]
[ 설명 ]
- AWS 서버 생성 후 MySQL 설치 진행

[ 완료 기준 ]
- AWS 서버 생성 후 MySQL 설치를 진행하고 각자 PC에서 서버 및 MySQL 접속 확인하기

**Comment by sypatrick** [comment]
putty로 접속후 ec_mall 데이터베이스 생성된 것 까지 확인했습니다.
